apiVersion: v1
kind: Service
metadata:
  name: linkding
spec:
  ports:
    - protocol: tcp
      port: 9090
      targetPort: 9090
      nodePort: 31090
  selector:
    app: linkding
  type: NodePort
